name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: master
          fetch-depth: '50'

      - name: Run The Pull Request Merger
        uses: agorararmard/pull-request-merger-action@main
